site_name: Cancer Prediction
site_url: https://github.com/<user-name>/cancer-prediction-fm480
repo_url: https://github.com/<user-name>/cancer-prediction-fm480
nav:
  - Home: index.md
  - cancer-prediction:
    - cancer model: cancer-prediction/cancer_model.md
    - streamlit app: cancer-prediction/streamlit_app.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for file changes